### ISSUE TITLE
Wrong config

### ISSUE THREAD

**Issue by qc00** [webjars/papa-parse#2]
Config says:

```
"papa-parse": "papa-parse"
```

but the actual repo has no dash in it. Could you also add a shim for the artifact without the dash so it matches DefinitelyTyped.

**Comment by jamesward** [comment]
I'm not exactly sure what change you are looking for.  Mind sending a PR with your proposed changes?

**Comment by qc00** [comment]
(Sorry. I was quite tired at that time.)
The requirejs config is pointing at a file called `papa-parse.js`. But if you look at http://www.webjars.org/listfiles/papa-parse/4.1.0, the actual file is `papaparse.js`.

**Comment by jamesward** [comment]
Resolved by #3
